### ISSUE TITLE
PLD and FoF windows, double weaves

### ISSUE THREAD

**Issue by crystal-prison** [StackBLU/UltimateCombo#2]
I've tested some consistent missed GCDs and drifts in the FoF window and have a few findings:

The Circle of Scorn and Expiacion double weave is not being executed properly. The order of execution for this double weave is Circle of Scorn first, then Expiacion. This is consistently incorrect in every FoF window, causing downtime on CoS.

At the 2min window (every other FoF use) Sepulchre should not be executed after Supplication.

Instead, it is held for the burst window, as follows:
Supplication > _FoF&Imperator_ > Confiteor > _Circle of Scorn&Expiacion_ > Blade of Faith > _Intervene_ > Blade of Truth > _Intervene_  > Blade of Valor > _Blade of Honor_ > Goring Blade > **Sepulchre** > Holy Spirit > Royal Authority

The rotation continues as normal again until the 4 min window, 6 min window, 8min window, etc. I'm not sure if this is possible to code into logic, otherwise the rotation is near perfect.

Thanks for your consideration.

Notes: 
FoF should never be delayed.
Always use Atonement immediately after Royal Authority.
Prioritize use of Sepulchre in FoF (over Holy Spirit)

**Comment by StackBLU** [comment]
Think I got it right - can you test and confirm with the latest version? (1.0.0.23)

Can you explain why Circle of Scorn comes before Expiacion as well?

**Comment by StackBLU** [comment]
I added timing checks for defensive abilities (Sheltron, Intervention, and Intervene cuz it's weak), so they won't be used if any of the higher priority abilities (FoF, CoS, Expiacion, and Imperator) have a cooldown remaining of less than 2. This should eliminate any weaving issues of less than 0.6 sec. It probably doesn't need to be 2 sec, but I can adjust it again if needed.

As for the usage order of Imperator > CoS > GCD > Expiacion, this is because of lag reduction and not checking for triple weaves. Since UC allows for triple weaves, this will likely always be the order it happens in. However, this also means that you're gaining 0.6 sec on your rotation. Pretty meaningless, but you're not losing any damage, so that's all that matters.

When I tested for 8 mins, I didn't lose any Divine Might stacks. Since conditions get a bit messy when you use things manually, can you record a long usage of what you'd normally do, then show it here? It likely has something to do with FoF window checking.

Current version: 1.0.0.26
